-- Crear base de datos dbCursos
CREATE DATABASE dbCurso;

-- Poner en uso
USE dbCURSO;

-- Crear la tabla PERSONA
CREATE TABLE PERSONA
(
     DNIPER CHAR(8),
     NOMPER VARCHAR(50),
     APEPER VARCHAR(80),
     FECNAPER DATE,
     CELPER CHAR(9),
     EMAPER VARCHAR(100),
     SEXPER CHAR(1),
     TIPPER CHAR(3),
     DISTPER VARCHAR(80),
     FECREGPER TIMESTAMP,
     PWSPER VARCHAR(20),
     CONSTRAINT  DNIPER_PK PRIMARY KEY (DNIPER)
);

-- Crear tabla DEPARTAMENTO
create table DEPARTAMENTO
(
    IDDEP int,
    NOMDEP varchar(50) NOT NULL,
    DNIPER char(8),
    SALJEFDEP DECIMAL(8,2),
    CONSTRAINT IDDEP_PK PRIMARY KEY(IDDEP)
);

-- Crear tabla HISTORICO
create table HISTORICO
(
    IDHIS int,
    DNIPER char (8),
    FECFINHIST date,
    TIPHIS char	(3),
    COMEHIST varchar (100),
    CONSTRAINT IDHIS_PK PRIMARY KEY(IDHIS)
);

-- Crear tabla EMPLEADO
create table EMPLEADO
(
    IDEMP int,
    DNIPER char (8),
    FECINGEMP date,
    CARGEMP varchar	(40),
    SALEMP decimal (6,2),
    IDDEP int,
    ESTEMP char (1),
    CONSTRAINT IDEMP_PK PRIMARY KEY(IDEMP)
);

-- Crear tabla INSCRIPCION
create table INSCRIPCION
(
    IDINSC int,
    DNIPER char (8),
    IDEMP int,
    IDOFER int,
    FECINS date,
    EVALINSC int,
    CONSTRAINT IDINSC_PK PRIMARY KEY(IDINSC)
);

-- Crear tabla OFERTA
create table OFERTA
(
    IDOFER int,
    CODCUR char (3),
    FECOFER date,
    FECINICCUROFER date,
    IDEMP int,
    CONSTRAINT IDOFER_PK PRIMARY KEY(IDOFER)
);

-- Crear tabla CURSO
create table CURSO
(
    CODCUR char (3),
    DESCUR varchar (30),
    CATCUR char (3),
    DURCUR int,
    CONSTRAINT CODCUR_PK PRIMARY KEY(CODCUR)
);

-- Relacionar la tabla PERSONA con DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA con HISTORICO
ALTER TABLE HISTORICO
ADD CONSTRAINT PERSONA_HISTORICO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA con EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT PERSONA_EMPLEADO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA con INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT PERSONA_INSCRIPCION_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla DEPARTAMENTO con EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT DEPARTAMENTO_EMPLEADO_IDDEP
FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO (IDDEP);

-- Relacionar la tabla EMPLEADO con INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT EMPLEADO_INSCRIPCION_IDEMP
FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla EMPLEADO con OFERTA
ALTER TABLE OFERTA
ADD CONSTRAINT EMPLEADO_OFERTA_IDEMP
FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla CURSO con OFERTA
ALTER TABLE OFERTA
ADD CONSTRAINT CURSO_OFERTA_CODCUR
FOREIGN KEY (CODCUR) REFERENCES CURSO (CODCUR);

